[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 3
[[menu.main]]
  name = "ğŸ¹"
  url = "/music"
  weight = 4
[[menu.main]]
  name = "ğŸ”–"
  weight = 5
  url = "/bookmarks"

[params]
  description = """
  a blog
"""
  tagline = """
  æœ¬ç«™ä¸å—å®¡æŸ¥é™åˆ¶  
  éƒ¨åˆ†å†…å®¹å¢™å†…éœ€VPN  
  æœ‰ä»€ä¹ˆæ„Ÿæƒ³æˆ–éœ€è¦çš„è¯·ç•™è¨€  
  (è”ç³»ä¿¡æ¯åªéœ€å¡«ä¸€æ¬¡)  
  æ¬è¿ä¸­
  """
  menu_item_separator = " - "

 [[params.social]]
    icon = "lastfm"
    name = "Lastfm"
    url = "https://www.last.fm/user/iloveWinnie"

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#afbac4"#text
  lightestColor = "#eeeeee"#title
  primaryColor = "#fc7777"#link color

#   darkestColor = "#777777"
#   darkColor = "#ffffff"
#   lightColor = "#888888"
#   lightestColor = "#777777"
#   primaryColor = "#57cc8a"

#  darkestColor = "#d35050"
#  darkColor = "#212121"
#  lightColor = "#f5e3e0"
#  lightestColor = "#f5f5f5"
#  primaryColor = "#ffffff"

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = 0
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = 0
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = 0